import {
  CommandId,
  MessageId,
  ProjectId,
  ProviderInstanceId,
  ThreadId,
  type OrchestrationMessage,
  type OrchestrationReadModel,
  type TurnStartSender,
} from "@t3tools/contracts";
import * as NodeServices from "@effect/platform-node/NodeServices";
import { expect, it } from "@effect/vitest";
import * as Effect from "effect/Effect";

import { decideOrchestrationCommand } from "./decider.ts";
import fixtureJson from "./turnStartDoor.f106e003.fixture.json" with { type: "json" };

const NOW = "2026-01-01T00:00:00.000Z";
const THREAD = ThreadId.make("thread-1");

/**
 * Both polarities of the turn-start door, replayed through the decider rather
 * than the door's own function, because the decider is where the door either
 * fires or does not and a door nobody calls is not a door.
 */

function makeReadModel(messages: ReadonlyArray<OrchestrationMessage>): OrchestrationReadModel {
  return {
    snapshotSequence: 0,
    projects: [],
    threads: [
      {
        id: THREAD,
        projectId: ProjectId.make("project-1"),
        title: "Thread",
        modelSelection: { instanceId: ProviderInstanceId.make("codex"), model: "gpt-5.4" },
        runtimeMode: "full-access",
        interactionMode: "default",
        branch: null,
        worktreePath: null,
        latestTurn: null,
        createdAt: NOW,
        updatedAt: NOW,
        archivedAt: null,
        settledOverride: null,
        settledAt: null,
        snoozedUntil: null,
        snoozedAt: null,
        deletedAt: null,
        messages,
        proposedPlans: [],
        activities: [],
        checkpoints: [],
        session: null,
      },
    ],
    updatedAt: NOW,
  };
}

function message(
  index: number,
  role: "user" | "assistant",
  text: string,
  sender?: TurnStartSender,
): OrchestrationMessage {
  return {
    id: MessageId.make(`msg-${index}`),
    role,
    text,
    turnId: null,
    streaming: false,
    ...(sender !== undefined ? { sender } : {}),
    createdAt: NOW,
    updatedAt: NOW,
  };
}

const startTurn = (
  index: number,
  text: string,
  sender: TurnStartSender,
  thread: OrchestrationMessage[],
) =>
  decideOrchestrationCommand({
    command: {
      type: "thread.turn.start",
      commandId: CommandId.make(`cmd-${index}`),
      threadId: THREAD,
      message: {
        messageId: MessageId.make(`msg-in-${index}`),
        role: "user",
        text,
        attachments: [],
      },
      runtimeMode: "full-access",
      interactionMode: "default",
      sender,
      createdAt: NOW,
    },
    readModel: makeReadModel(thread),
  });

type FixtureMessage = {
  readonly role: "user" | "assistant" | "system";
  readonly text: string;
  readonly sender?: TurnStartSender;
};

type Fixture = {
  readonly threadId: string;
  readonly counts: {
    readonly total: number;
    readonly user: number;
    readonly assistant: number;
    readonly breather: number;
    readonly distinctBreatherTexts: number;
  };
  readonly messages: ReadonlyArray<FixtureMessage>;
};

// Exported read-only from ThroughLine's own state database; regenerated by
// _meta/scripts/buildTurnStartDoorFixture.mts in this component's run record.
const fixture = fixtureJson as unknown as Fixture;

it.layer(NodeServices.layer)("turn-start door", (it) => {
  /**
   * POSITIVE POLARITY — the real drain, replayed.
   *
   * Every message of thread f106e003 in its real order: 2,413 records, 1,128
   * user messages, 1,285 assistant answers, 1,116 of the user messages sent by
   * com.ryan.seat-breather over twelve days. The seat answered every one.
   *
   * The two numbers this test pins are the two that decide whether the door
   * works at all:
   *
   *  - 1,029 DISTINCT TEXTS among the 1,116 breather messages. A door keyed on
   *    the raw text would refuse 87 and let 1,029 through. If a future change
   *    makes the hash literal again, this assertion is what catches it.
   *  - 3 BREATHER TURNS ALLOWED after the last human message on the thread.
   *    Not "3 per distinct text" — three, total, until a person speaks again.
   */
  it.effect("refuses the f106e003 breather storm after three turns", () =>
    Effect.gen(function* () {
      expect(fixture.counts.breather).toBe(1116);
      expect(fixture.counts.distinctBreatherTexts).toBe(1029);

      const thread: OrchestrationMessage[] = [];
      let allowedTurns = 0;
      let breatherAllowed = 0;
      let breatherRefused = 0;
      let breatherAllowedSinceLastHuman = 0;
      const refusalReasons = new Map<string, number>();
      let index = 0;

      for (const entry of fixture.messages) {
        index += 1;
        if (entry.role !== "user") {
          thread.push(message(index, "assistant", entry.text));
          continue;
        }
        const sender = entry.sender ?? "unknown";
        const decided = yield* startTurn(index, entry.text, sender, thread);
        const events = Array.isArray(decided) ? decided : [decided];
        const isBreather = entry.text.startsWith("BREATHER:");
        const refusal = events.find((event) => event.type === "thread.turn-start-refused");

        if (refusal === undefined) {
          allowedTurns += 1;
          if (isBreather) {
            breatherAllowed += 1;
            breatherAllowedSinceLastHuman += 1;
          }
          if (sender === "human-composer") {
            breatherAllowedSinceLastHuman = 0;
          }
          // Only an allowed turn puts a message on the thread, which is what
          // makes the next decision see the same history the server would.
          thread.push(message(index, "user", entry.text, sender));
          continue;
        }

        expect(events).toHaveLength(1);
        if (refusal.type === "thread.turn-start-refused") {
          refusalReasons.set(
            refusal.payload.reason,
            (refusalReasons.get(refusal.payload.reason) ?? 0) + 1,
          );
          // A refusal is never silent: it names who was refused, on what shape,
          // after how many turns, against what budget.
          expect(refusal.payload.sender).toBe(sender);
          expect(refusal.payload.threadId).toBe(THREAD);
          expect(refusal.payload.textShapeHash).toHaveLength(64);
          expect(refusal.payload.budget).toBe(3);
          expect(refusal.payload.deliveryCount).toBeGreaterThanOrEqual(3);
          expect(refusal.payload.detail.length).toBeGreaterThan(0);
        }
        if (isBreather) breatherRefused += 1;
      }

      // Measured against the real history on 2026-09-12.
      expect(breatherAllowedSinceLastHuman).toBe(3);
      expect(breatherAllowed).toBe(8);
      expect(breatherRefused).toBe(1108);
      expect(breatherAllowed + breatherRefused).toBe(fixture.counts.breather);
      expect(allowedTurns).toBe(20);
      expect(refusalReasons.get("budget-exhausted")).toBe(1108);
    }),
  );

  /**
   * NEGATIVE POLARITY — ordinary work is untouched.
   *
   * Two different human messages and two different agent messages on one
   * thread. Four turns start, nothing is refused. If the door ever starts
   * refusing here it has stopped being a budget and become a tax.
   */
  it.effect("passes two human and two agent messages on one thread", () =>
    Effect.gen(function* () {
      const thread: OrchestrationMessage[] = [];
      const sequence: ReadonlyArray<{ text: string; sender: TurnStartSender }> = [
        { text: "Land the tower cutover and report what moved.", sender: "human-composer" },
        { text: "Now check whether the broker answered on 19445.", sender: "human-composer" },
        { text: "ComsNet request 1: review the diff on apps/server.", sender: "comsnet-send" },
        { text: "ComsNet request 2: the review is in, summarise it.", sender: "comsnet-send" },
      ];

      let started = 0;
      let refused = 0;
      let index = 0;
      for (const entry of sequence) {
        index += 1;
        const decided = yield* startTurn(index, entry.text, entry.sender, thread);
        const events = Array.isArray(decided) ? decided : [decided];
        if (events.some((event) => event.type === "thread.turn-start-refused")) {
          refused += 1;
          continue;
        }
        started += 1;
        expect(events.some((event) => event.type === "thread.message-sent")).toBe(true);
        expect(events.some((event) => event.type === "thread.turn-start-requested")).toBe(true);
        thread.push(message(index, "user", entry.text, entry.sender));
        // Each turn is answered, exactly as a working thread behaves.
        thread.push(message(index + 100, "assistant", "Done."));
      }

      expect(started).toBe(4);
      expect(refused).toBe(0);
    }),
  );

  /**
   * The measurement that killed the obvious design, kept as a live assertion.
   *
   * The order this door was built from defined a reset as "a new assistant
   * record or a new human message". Thread f106e003 produced 1,285 assistant
   * records against 1,128 user messages, so under that rule the loop refills
   * the budget it is meant to exhaust. Here a daemon is answered every single
   * time and is still stopped at three.
   */
  it.effect("an assistant answer does not refill a machine sender's budget", () =>
    Effect.gen(function* () {
      const thread: OrchestrationMessage[] = [];
      let started = 0;
      let refused = 0;
      for (let index = 1; index <= 10; index += 1) {
        const decided = yield* startTurn(
          index,
          `BREATHER: seat is quiet ${index} min with an open record.`,
          "dispatch-socket",
          thread,
        );
        const events = Array.isArray(decided) ? decided : [decided];
        if (events.some((event) => event.type === "thread.turn-start-refused")) {
          refused += 1;
          continue;
        }
        started += 1;
        thread.push(
          message(
            index,
            "user",
            `BREATHER: seat is quiet ${index} min with an open record.`,
            "dispatch-socket",
          ),
        );
        thread.push(message(index + 100, "assistant", "Acknowledged, continuing."));
      }
      expect(started).toBe(3);
      expect(refused).toBe(7);
    }),
  );

  /**
   * A human message is the only thing that refills the budget, and it does.
   */
  it.effect("a human message reopens the window for a machine sender", () =>
    Effect.gen(function* () {
      const thread: OrchestrationMessage[] = [];
      const drive = (index: number) =>
        startTurn(index, `BREATHER: quiet ${index} min.`, "dispatch-socket", thread);

      for (let index = 1; index <= 3; index += 1) {
        yield* drive(index);
        thread.push(message(index, "user", `BREATHER: quiet ${index} min.`, "dispatch-socket"));
        thread.push(message(index + 100, "assistant", "ok"));
      }

      const blocked = yield* drive(4);
      const blockedEvents = Array.isArray(blocked) ? blocked : [blocked];
      expect(blockedEvents[0]?.type).toBe("thread.turn-start-refused");

      thread.push(
        message(200, "user", "Stop what you are doing and tell me why.", "human-composer"),
      );

      const reopened = yield* drive(5);
      const reopenedEvents = Array.isArray(reopened) ? reopened : [reopened];
      expect(reopenedEvents.some((event) => event.type === "thread.turn-start-requested")).toBe(
        true,
      );
    }),
  );

  /**
   * The second refusal reason, which the real history never exercised because
   * the seat answered every delivery. A sender that re-fires before anything at
   * all has happened is refused on the spot, independently of the budget.
   */
  it.effect("refuses a repeat fired before the thread produced anything", () =>
    Effect.gen(function* () {
      const text = "BREATHER: seat is quiet 4 min with an open record.";
      const thread: OrchestrationMessage[] = [message(1, "user", text, "dispatch-socket")];
      const decided = yield* startTurn(2, text, "dispatch-socket", thread);
      const events = Array.isArray(decided) ? decided : [decided];
      expect(events).toHaveLength(1);
      expect(events[0]?.type).toBe("thread.turn-start-refused");
      if (events[0]?.type === "thread.turn-start-refused") {
        expect(events[0].payload.reason).toBe("unchanged-repeat");
        expect(events[0].payload.deliveryCount).toBe(1);
      }
    }),
  );

  /**
   * A sender that never names itself is budgeted, not trusted. This is what
   * makes every producer that predates the `sender` field safe by default.
   */
  it.effect("treats an unnamed sender as machine, not human", () =>
    Effect.gen(function* () {
      const thread: OrchestrationMessage[] = [];
      let refusedAt = 0;
      for (let index = 1; index <= 5; index += 1) {
        const decided = yield* decideOrchestrationCommand({
          command: {
            type: "thread.turn.start",
            commandId: CommandId.make(`cmd-anon-${index}`),
            threadId: THREAD,
            message: {
              messageId: MessageId.make(`msg-anon-${index}`),
              role: "user",
              text: `continue working toward the active thread goal (${index})`,
              attachments: [],
            },
            runtimeMode: "full-access",
            interactionMode: "default",
            createdAt: NOW,
          },
          readModel: makeReadModel(thread),
        });
        const events = Array.isArray(decided) ? decided : [decided];
        if (events.some((event) => event.type === "thread.turn-start-refused")) {
          refusedAt = index;
          break;
        }
        thread.push(
          message(
            index,
            "user",
            `continue working toward the active thread goal (${index})`,
            "unknown",
          ),
        );
        thread.push(message(index + 100, "assistant", "working"));
      }
      expect(refusedAt).toBe(4);
    }),
  );
});
